using Microsoft.EntityFrameworkCore;

namespace StoneAge.Infrastructure.Persistence;

public static class DatabaseSchemaUpgrade
{
    public static async Task ApplyAsync(GameDbContext db, CancellationToken cancellationToken = default)
    {
        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE characters
            ADD COLUMN IF NOT EXISTS "Stone" integer NOT NULL DEFAULT 1000;

            CREATE TABLE IF NOT EXISTS character_items (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CharacterId" bigint NOT NULL,
                "ItemId" integer NOT NULL,
                "Quantity" integer NOT NULL,
                "Slot" smallint NOT NULL DEFAULT 0,
                "EquippedSlot" smallint NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "FK_character_items_characters_CharacterId"
                    FOREIGN KEY ("CharacterId") REFERENCES characters ("Id") ON DELETE CASCADE
            );

            ALTER TABLE character_items ADD COLUMN IF NOT EXISTS "Slot" smallint NOT NULL DEFAULT 0;
            ALTER TABLE character_items ADD COLUMN IF NOT EXISTS "EquippedSlot" smallint NULL;

            WITH ranked AS (
                SELECT "Id", ROW_NUMBER() OVER (PARTITION BY "CharacterId" ORDER BY "Id") - 1 AS new_slot
                FROM character_items
            )
            UPDATE character_items ci
            SET "Slot" = ranked.new_slot
            FROM ranked
            WHERE ci."Id" = ranked."Id";

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_character_items_CharacterId_ItemId"
                ON character_items ("CharacterId", "ItemId");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_character_items_CharacterId_Slot"
                ON character_items ("CharacterId", "Slot");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_character_items_CharacterId_EquippedSlot"
                ON character_items ("CharacterId", "EquippedSlot")
                WHERE "EquippedSlot" IS NOT NULL;

            CREATE TABLE IF NOT EXISTS character_pets (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CharacterId" bigint NOT NULL,
                "MonsterId" integer NOT NULL,
                "Name" varchar(24) NOT NULL,
                "Level" integer NOT NULL DEFAULT 1,
                "Experience" bigint NOT NULL DEFAULT 0,
                "Hp" integer NOT NULL,
                "MaxHp" integer NOT NULL,
                "Attack" integer NOT NULL,
                "Defense" integer NOT NULL,
                "Agility" integer NOT NULL,
                "Loyalty" integer NOT NULL DEFAULT 50,
                "Earth" smallint NOT NULL,
                "Water" smallint NOT NULL,
                "Fire" smallint NOT NULL,
                "Wind" smallint NOT NULL,
                "IsActive" boolean NOT NULL DEFAULT FALSE,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "FK_character_pets_characters_CharacterId"
                    FOREIGN KEY ("CharacterId") REFERENCES characters ("Id") ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_character_pets_CharacterId_IsActive"
                ON character_pets ("CharacterId", "IsActive") WHERE "IsActive" = TRUE;

            CREATE TABLE IF NOT EXISTS character_pet_skills (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CharacterPetId" bigint NOT NULL,
                "Slot" smallint NOT NULL,
                "SkillId" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "FK_character_pet_skills_character_pets_CharacterPetId"
                    FOREIGN KEY ("CharacterPetId") REFERENCES character_pets ("Id") ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_character_pet_skills_CharacterPetId_Slot"
                ON character_pet_skills ("CharacterPetId", "Slot");
            """, cancellationToken);
    }
}
