using Microsoft.EntityFrameworkCore;

namespace StoneAge.Infrastructure.Persistence;

public static class DatabaseSchemaUpgrade
{
    public static async Task ApplyAsync(GameDbContext db, CancellationToken cancellationToken = default)
    {
        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE characters
            ADD COLUMN IF NOT EXISTS "Stone" integer NOT NULL DEFAULT 1000;

            CREATE TABLE IF NOT EXISTS character_items (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CharacterId" bigint NOT NULL,
                "ItemId" integer NOT NULL,
                "Quantity" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "FK_character_items_characters_CharacterId"
                    FOREIGN KEY ("CharacterId") REFERENCES characters ("Id") ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_character_items_CharacterId_ItemId"
                ON character_items ("CharacterId", "ItemId");
            """, cancellationToken);
    }
}
